version: "3"

services:
  # app
  app:
    image: node:current-alpine
    working_dir: /usr/src/app
    volumes:
      - ./services/app:/usr/src/app
    command: [sh, -c npm run start]
    ports:
      - 3001:3001

