POST http://localhost:3001/api/v1/books
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="title"

サンプル書籍
--MyBoundary
Content-Disposition: form-data; name="status"

0
--MyBoundary
Content-Disposition: form-data; name="coverImage"; filename="sample.jpg"
Content-Type: image/jpeg

< ../sample.jpg

--MyBoundary--

### 書籍一覧
GET http://localhost:3001/api/v1/books